# Generated by Django 5.0.2 on 2024-02-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_rename_item_pricing_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='item_type',
        ),
    ]
