# Generated by Django 5.0.2 on 2024-02-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_rename_type_item_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='base_price',
            new_name='fix_price',
        ),
    ]
